# Generated by Django 4.2.6 on 2023-11-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0002_rename_detail_kfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfa',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/%Y/%m/%d/'),
        ),
    ]
