# Generated by Django 4.2.6 on 2023-11-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0003_kfa_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfa',
            name='hook_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
