# Generated by Django 4.2.6 on 2023-11-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='kfa',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='kfa',
            name='name',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='kfa',
            name='option_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
