# Generated by Django 4.2.5 on 2023-11-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0006_delete_product_kfa_base_price_kfa_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kfa',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/%Y/%m/%d/'),
        ),
    ]
