# Generated by Django 4.2.5 on 2023-11-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0007_kfa_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kfa',
            name='detail_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/상품상세이미지/'),
        ),
        migrations.AlterField(
            model_name='kfa',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/상품이미지/'),
        ),
    ]
