# Generated by Django 4.2.5 on 2023-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KFA', '0008_alter_kfa_detail_image_alter_kfa_head_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kfa',
            old_name='detail_image',
            new_name='detail_image1',
        ),
        migrations.AddField(
            model_name='kfa',
            name='detail_image2',
            field=models.ImageField(blank=True, upload_to='KFA/images/상품상세이미지/'),
        ),
        migrations.AddField(
            model_name='kfa',
            name='size_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/상품상세이미지/'),
        ),
    ]
