# Generated by Django 4.2.5 on 2023-12-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='ask/files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ask',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='ask/images/%Y/%m/%d'),
        ),
    ]
