# Generated by Django 4.2.5 on 2023-12-03 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0004_alter_ask_content_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_comments', to='ask.ask'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_comment_authors', to=settings.AUTH_USER_MODEL),
        ),
    ]
