# Generated by Django 4.2.5 on 2023-12-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_alter_comment_ask_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
