# Generated by Django 4.2.5 on 2023-12-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('memberid', models.TextField()),
                ('pw', models.TextField()),
                ('phonenumber', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
    ]
