# Generated by Django 4.2.6 on 2023-11-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='cont',
            new_name='content',
        ),
    ]
