# Generated by Django 4.2.6 on 2023-11-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_cont_event_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='event/imges/%Y/%m/%d/'),
        ),
    ]
