# Generated by Django 4.2.5 on 2023-11-26 02:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
