# Generated by Django 4.2.6 on 2023-11-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OOTD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ootd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ootd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
