# Generated by Django 4.2.6 on 2023-11-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OOTD', '0002_ootd_updated_at_alter_ootd_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ootd',
            old_name='content',
            new_name='cont',
        ),
        migrations.AlterField(
            model_name='ootd',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
