# Generated by Django 4.2.6 on 2023-11-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OOTD', '0003_rename_content_ootd_cont_alter_ootd_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ootd',
            old_name='cont',
            new_name='content',
        ),
    ]
