# Generated by Django 4.2.6 on 2023-11-26 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OOTD', '0005_remove_ootd_updated_at_ootd_head_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ootd',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ootd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ootd',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
