# Generated by Django 4.2.5 on 2023-12-03 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OOTD', '0008_alter_comment_author_alter_comment_ootd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ootd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OOTD.ootd'),
        ),
    ]
