# Generated by Django 4.2.6 on 2023-11-07 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KLEAGUE', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='KLEAGUE',
        ),
    ]
