# Generated by Django 4.2.6 on 2023-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KLEAGUE', '0002_rename_product_kleague'),
    ]

    operations = [
        migrations.AddField(
            model_name='kleague',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='KLEAGUE/images/%Y/%m/%d/'),
        ),
    ]
