# Generated by Django 4.2.6 on 2023-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KLEAGUE', '0004_kleague_base_price_kleague_hook_text_kleague_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kleague',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='KFA/images/%Y/%m/%d/'),
        ),
    ]
