# Generated by Django 4.2.5 on 2023-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KLEAGUE', '0005_alter_kleague_head_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kleague',
            name='hook_text',
        ),
        migrations.AddField(
            model_name='kleague',
            name='league_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
