# Generated by Django 4.2.5 on 2023-11-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KLEAGUE', '0006_remove_kleague_hook_text_kleague_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kleague',
            name='detail_image1',
            field=models.ImageField(blank=True, upload_to='KLEAGUE/images/상품상세이미지/'),
        ),
        migrations.AddField(
            model_name='kleague',
            name='detail_image2',
            field=models.ImageField(blank=True, upload_to='KLEAGUE/images/상품상세이미지/'),
        ),
        migrations.AddField(
            model_name='kleague',
            name='size_image',
            field=models.ImageField(blank=True, upload_to='KLEAGUE/images/상품상세이미지/'),
        ),
        migrations.AlterField(
            model_name='kleague',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='KLEAGUE/images/상품이미지/'),
        ),
    ]
