# Generated by Django 4.2.5 on 2023-11-26 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KLEAGUE', '0007_kleague_detail_image1_kleague_detail_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kleague',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kleague',
            name='cont',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
