# Generated by Django 4.2.5 on 2023-11-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='notice/images/%Y/%m/%d'),
        ),
    ]
