# Generated by Django 4.2.5 on 2023-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='notice/files/%Y/%m/%d/'),
        ),
    ]
