# Generated by Django 4.2.5 on 2023-11-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_alter_notice_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='cont',
        ),
    ]
