# Generated by Django 4.2.5 on 2023-11-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_updated_at_alter_cart_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
